print("heooooo")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
print("my name is prathamesh")
